import React from "react";
import "./globals.css";
import Navbar from "./components/Header/Navbar";
import CardTemp from "./components/shoppingCard/CardTemp";
import Footer from "./components/Footer/Footer";
import Sidebar from "./components/sidebar/sidebar";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
          <Sidebar  />
            {children}
            <CardTemp />
            
        <Footer />
      </body>
    </html>
  );
}
